export const list = {
  "ar-SA": {"Language": "Arabic", "Region":"Saudi Arabia", "Description":"Arabic (Saudi Arabia)"},
  "bn-BD": {"Language": "Bangla", "Region":"Bangladesh", "Description":"Bangla (Bangladesh)"},
  "bn-IN": {"Language": "Bangla", "Region":"India", "Description":"Bangla (India)"},
  "cs-CZ": {"Language": "Czech", "Region":"Czech Republic", "Description":"Czech (Czech Republic)"},
  "da-DK": {"Language": "Danish", "Region":"Denmark", "Description":"Danish (Denmark)"},
  "de-AT": {"Language": "German", "Region":"Austria", "Description":"Austrian German"},
  "de-CH": {"Language": "German", "Region":"Switzerland", "Description":"\"Swiss\" German"},
  "de-DE": {"Language": "German", "Region":"Germany", "Description":"Standard German (as spoken in Germany)"},
  "el-GR": {"Language": "Greek", "Region":"Greece", "Description":"Modern Greek"},
  "en-AU": {"Language": "English", "Region":"Australia", "Description":"Australian English"},
  "en-CA": {"Language": "English", "Region":"Canada", "Description":"Canadian English"},
  "en-GB": {"Language": "English", "Region":"United Kingdom", "Description":"British English"},
  "en-IE": {"Language": "English", "Region":"Ireland", "Description":"Irish English"},
  "en-IN": {"Language": "English", "Region":"India", "Description":"Indian English"},
  "en-NZ": {"Language": "English", "Region":"New Zealand", "Description":"New Zealand English"},
  "en-US": {"Language": "English", "Region":"United States", "Description":"US English"},
  "en-ZA": {"Language": "English", "Region":"South Africa", "Description":"English (South Africa)"},
  "es-AR": {"Language": "Spanish", "Region":"Argentina", "Description":"Argentine Spanish"},
  "es-CL": {"Language": "Spanish", "Region":"Chile", "Description":"Chilean Spanish"},
  "es-CO": {"Language": "Spanish", "Region":"Columbia", "Description":"Colombian Spanish"},
  "es-ES": {"Language": "Spanish", "Region":"Spain", "Description":"Castilian Spanish (as spoken in Central-Northern Spain)"},
  "es-MX": {"Language": "Spanish", "Region":"Mexico", "Description":"Mexican Spanish"},
  "es-US": {"Language": "Spanish", "Region":"United States", "Description":"American Spanish"},
  "fi-FI": {"Language": "Finnish", "Region":"Finland", "Description":"Finnish (Finland)"},
  "fr-BE": {"Language": "French", "Region":"Belgium", "Description":"Belgian French"},
  "fr-CA": {"Language": "French", "Region":"Canada", "Description":"Canadian French"},
  "fr-CH": {"Language": "French", "Region":"Switzerland", "Description":"\"Swiss\" French"},
  "fr-FR": {"Language": "French", "Region":"France", "Description":"Standard French (especially in France)"},
  "he-IL": {"Language": "Hebrew", "Region":"Israel", "Description":"Hebrew (Israel)"},
  "hi-IN": {"Language": "Hindi", "Region":"India", "Description":"Hindi (India)"},
  "hu-HU": {"Language": "Hungarian", "Region":"Hungary", "Description":"Hungarian (Hungary)"},
  "id-ID": {"Language": "Indonesian", "Region":"Indonesia", "Description":"Indonesian (Indonesia)"},
  "it-CH": {"Language": "Italian", "Region":"Switzerland", "Description":"\"Swiss\" Italian"},
  "it-IT": {"Language": "Italian", "Region":"Italy", "Description":"Standard Italian (as spoken in Italy)"},
  "ja-JP": {"Language": "Japanese", "Region":"Japan", "Description":"Japanese (Japan)"},
  "ko-KR": {"Language": "Korean", "Region":"Republic of Korea", "Description":"Korean (Republic of Korea)"},
  "nl-BE": {"Language": "Dutch", "Region":"Belgium", "Description":"Belgian Dutch"},
  "nl-NL": {"Language": "Dutch", "Region":"The Netherlands", "Description":"Standard Dutch (as spoken in The Netherlands)"},
  "no-NO": {"Language": "Norwegian", "Region":"Norway", "Description":"Norwegian (Norway)"},
  "pl-PL": {"Language": "Polish", "Region":"Poland", "Description":"Polish (Poland)"},
  "pt-BR": {"Language": "Portuguese", "Region":"Brazil", "Description":"Brazilian Portuguese"},
  "pt-PT": {"Language": "Portuguese", "Region":"Portugal", "Description":"European Portuguese (as written and spoken in Portugal)"},
  "ro-RO": {"Language": "Romanian", "Region":"Romania", "Description":"Romanian (Romania)"},
  "ru-RU": {"Language": "Russian", "Region":"Russian Federation", "Description":"Russian (Russian Federation)"},
  "sk-SK": {"Language": "Slovak", "Region":"Slovakia", "Description":"Slovak (Slovakia)"},
  "sv-SE": {"Language": "Swedish", "Region":"Sweden", "Description":"Swedish (Sweden)"},
  "ta-IN": {"Language": "Tamil", "Region":"India", "Description":"Indian Tamil"},
  "ta-LK": {"Language": "Tamil", "Region":"Sri Lanka", "Description":"Sri Lankan Tamil"},
  "th-TH": {"Language": "Thai", "Region":"Thailand", "Description":"Thai (Thailand)"},
  "tr-TR": {"Language": "Turkish", "Region":"Turkey", "Description":"Turkish (Turkey)"},
  "zh-CN": {"Language": "Chinese", "Region":"China", "Description":"Mainland China, simplified characters"},
  "zh-HK": {"Language": "Chinese", "Region":"Hong Kong", "Description":"Hong Kong, traditional characters"},
  "zh-TW": {"Language": "Chinese", "Region":"Taiwan", "Description":"Taiwan, traditional characters"}
}